# Generated by Django 3.1 on 2020-08-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('is_buy_forever', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('poster', models.ImageField(upload_to='serials')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('genres', models.ManyToManyField(related_name='serials', to='core.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='series')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='core.serial')),
            ],
        ),
    ]
