# Generated by Django 3.1 on 2020-08-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_showcase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShowCase',
            new_name='ShowCases',
        ),
    ]
